<?php /* @var $this Zero1_Crondoctor_Block_Adminhtml_Visual */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getFormHtml() ?>
<div id="visual-container"></div>