<?php
/* @var $this Zero1_Crondoctor_Block_Adminhtml_Visual_Visual */
/* @var $schedule Zero1_Crondoctor_Model_Schedule */
$schedule = $this->getSchedule();
$to = $this->getTo();
$from = $this->getFrom();

$defaultWidth = 1200;
$minMinuteDisplayWith = 12;

$diference = ($to - $from) / 60;
$diference -= ($diference % 60);

$naturalWidth = ($diference * $minMinuteDisplayWith);
$naturalWidth += 40; //padding for time display
/* @var $job Zero1_Crondoctor_Model_Schedule_Job */
/* @var $process Zero1_Crondoctor_Model_Schedule_Job_Process */

$jobHtml = array();
foreach($schedule->getSchedule() as $jobCode => $job){
	list($html, $maxDepth) = $this->getJobHtml($job, $from, $naturalWidth);
	$jobHtml[$jobCode] = array(
		'html' => $html,
		'max_depth' => $maxDepth,
	);
}


?>
<div style="margin: 20px;">
	<div style="float: left; padding: 40px 0 0 0; border: solid 1px #000000; border-right-width: 0; overflow: visible;">
		<?php foreach($schedule->getSchedule() as $jobCode => $job): ?>
			<div style="height: <?php echo $jobHtml[$jobCode]['max_depth'] * 10; ?>px; border-bottom: solid #000000 2px; background-color: orange; overflow: visible; padding: 0 10px;">
				<?php echo $jobCode; ?><br />
				(<?php echo $job->getCronExpr(); ?>)
			</div>
		<?php endforeach; ?>
	</div>
	<div style="float: left; border: solid 1px #000000;
		width: <?php echo $defaultWidth; ?>px;
		overflow-x: scroll;"
		>
		<div class="timebar" style="width: <?php echo $naturalWidth; ?>px;">
			<div style="float: left; width: 40px; height: 40px; overflow: hidden;">

				<div style="width: 40px; height: 20px; text-align: center;"><?php echo strftime('%H:%M', $from); ?></div>
				<div style="float: left; width: 18px; height: 20px; border-right: solid; 2px #000000;"></div>
				<div style="float: left; width: 18px; height: 20px; border-left: solid; 2px; #000000;"></div>

			</div>
			<?php
			$oneHour = (60 * 60);
			for($timeCount = ($from + $oneHour); $timeCount <= $to; $timeCount += $oneHour): ?>
				<div style="float: left; width: <?php echo (($minMinuteDisplayWith * 60) - 40); ?>px; height: 40px;"></div>

				<div style="float: left; width: 40px; height: 40px; overflow: hidden;">

					<div style="width: 40px; height: 20px; text-align: center;"><?php echo strftime('%H:%M', $timeCount); ?></div>
					<div style="float: left; width: 18px; height: 20px; border-right: solid #000000 2px;"></div>
					<div style="float: left; width: 18px; height: 20px; border-left: solid #000000 2px;"></div>

				</div>
			<?php endfor; ?>
			<div style="clear: both;"></div>
		</div>

		<?php foreach($schedule->getSchedule() as $jobCode => $job): ?>
			<?php echo $jobHtml[$jobCode]['html']; ?>
		<?php endforeach; ?>
	</div>
	<div style="float: left; padding: 40px 0 0 0; border: solid 1px #000000; border-left-width: 0; overflow: visible; width: 200px;">
		<?php foreach($schedule->getSchedule() as $jobCode => $job): ?>
			<div style="height: <?php echo $jobHtml[$jobCode]['max_depth'] * 10; ?>px; border-bottom: solid #000000 2px; overflow-y: scroll; padding: 0 10px;">
				<?php foreach($job->getStats() as $key => $data): ?>
					<?php echo $data['name'].': '.$data['value'].'<br />'; ?>
					<?php //echo $data['description']; ?>
				<?php endforeach; ?>
			</div>
		<?php endforeach; ?>
	</div>
</div>